on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Use Go Action  
        id: use-go-action
        uses: https://git.beisel.it/florian/gitea-release-drafter@main
