name: Test Changes on Push

on:
  push:

jobs:
  build-vet-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21' # Specify your Go version
    - name: Build
      run: go build ./...
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test ./...
